# Generated by Django 4.2 on 2026-03-10 21:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('is_active', models.BooleanField(db_column='ativo', default=True)),
                ('is_staff', models.BooleanField(db_column='staff', default=False)),
                ('date_joined', models.DateTimeField(db_column='dt_cadastro', default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'tb_usuario',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], db_column='tipo', max_length=2)),
                ('cpf', models.CharField(blank=True, db_column='cpf', max_length=11, null=True, unique=True)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, db_column='cnpj', max_length=14, null=True, unique=True)),
                ('razao_social', models.CharField(blank=True, db_column='razao_soc', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, db_column='telefone', max_length=20, null=True)),
                ('celular', models.CharField(blank=True, db_column='celular', max_length=20, null=True)),
                ('logradouro', models.CharField(blank=True, db_column='logradouro', max_length=100, null=True)),
                ('numero', models.CharField(blank=True, db_column='numero', max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, db_column='complemento', max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, db_column='bairro', max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, db_column='cidade', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_column='estado', max_length=2, null=True)),
                ('cep', models.CharField(blank=True, db_column='cep', max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, db_column='endereco', max_length=200, null=True)),
                ('permissoes_devolucao', models.CharField(blank=True, db_column='perms_devolucao', default='criar,visualizar,editar,deletar', help_text='Permissões separadas por vírgula: criar, visualizar, editar, deletar', max_length=100, null=True)),
                ('usuario', models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'tb_cliente',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_devolucao_dias', models.PositiveIntegerField(db_column='prazo_dev_dias', default=30)),
            ],
            options={
                'verbose_name': 'Configuracao do Sistema',
                'verbose_name_plural': 'Configuracoes do Sistema',
                'db_table': 'tb_configuracao',
            },
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_processo', 'Em Processo'), ('concluido', 'Concluído'), ('recusada', 'Recusada')], db_column='status', default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='dt_criacao')),
                ('observacao_geral', models.CharField(blank=True, db_column='obs_geral', max_length=200, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='id_cliente', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='devolucao.cliente')),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
                'db_table': 'tb_devolucao',
                'ordering': ['-data_criacao'],
                'permissions': [('pode_criar_devolucao', 'Pode criar devoluções'), ('pode_editar_devolucao', 'Pode editar devoluções'), ('pode_excluir_devolucao', 'Pode excluir devoluções'), ('pode_ver_todas_devolucoes', 'Pode ver todas as devoluções'), ('pode_gerenciar_usuarios', 'Pode gerenciar usuários/admins')],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, db_column='codprod', null=True)),
                ('descricao', models.CharField(blank=True, db_column='descricao', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'tb_produto',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(blank=True, db_column='nunota', max_length=50, null=True, unique=True)),
                ('data_emissao', models.DateField(blank=True, db_column='dt_emissao', help_text='Data de emissao da nota. Usada para calcular prazo de devolucao.', null=True)),
                ('arquivo_pdf', models.FileField(blank=True, db_column='pdf', null=True, upload_to='uploads/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='devolucao.cliente')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'db_table': 'tb_notafiscal',
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(db_column='qtd')),
                ('nota_fiscal', models.ForeignKey(db_column='id_notafiscal', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='devolucao.notafiscal')),
                ('produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.PROTECT, to='devolucao.produto')),
            ],
            options={
                'verbose_name': 'Item da Nota',
                'verbose_name_plural': 'Itens da Nota',
                'db_table': 'tb_itens_nota',
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_devolvida', models.PositiveIntegerField(db_column='qtd_devolvida')),
                ('motivo', models.CharField(blank=True, choices=[('produto_danificado', 'Produto danificado'), ('erro_pedido', 'Erro no pedido'), ('prazo_vencido', 'Prazo de validade vencido'), ('outro', 'Outro')], db_column='motivo', max_length=50, null=True)),
                ('observacao', models.CharField(blank=True, db_column='obs', max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, db_column='foto', null=True, upload_to='uploads/fotos_devolucao/')),
                ('devolucao', models.ForeignKey(db_column='id_devolucao', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='devolucao.devolucao')),
                ('produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.PROTECT, to='devolucao.produto')),
            ],
            options={
                'verbose_name': 'Item da Devolução',
                'verbose_name_plural': 'Itens da Devolução',
                'db_table': 'tb_itens_devolucao',
            },
        ),
        migrations.AddField(
            model_name='devolucao',
            name='nota_fiscal',
            field=models.ForeignKey(db_column='id_notafiscal', on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='devolucao.notafiscal'),
        ),
        migrations.AddField(
            model_name='devolucao',
            name='usuario_criador',
            field=models.ForeignKey(blank=True, db_column='id_usuario_criador', help_text='Usuário que criou a devolução', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
