# Generated by Django 4.2 on 2026-04-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(db_column='texto')),
                ('lido', models.BooleanField(db_column='lido', default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_criacao')),
                ('devolucao', models.ForeignKey(blank=True, db_column='id_devolucao', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat', to='devolucao.devolucao')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem Chat',
                'verbose_name_plural': 'Mensagens Chat',
                'db_table': 'tb_mensagem_chat',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='mensagemchat',
            index=models.Index(fields=['devolucao', '-criado_em'], name='tb_mensagem_id_devo_e2859b_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagemchat',
            index=models.Index(fields=['usuario', '-criado_em'], name='tb_mensagem_id_usua_9af2ed_idx'),
        ),
    ]
