# Generated by Django 4.2 on 2026-04-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0002_mensagemchat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='whatsapp_numero',
            field=models.CharField(blank=True, db_column='whatsapp_numero', help_text='Número de WhatsApp para contato (formato: +55 11 99999-9999)', max_length=20, null=True),
        ),
    ]
