# Generated by Django 4.2 on 2026-04-07 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0003_configuracaosistema_whatsapp_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteVinculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_column='ativo', default=True, help_text='Se False, o cliente não aparecerá nos dropdowns do usuário')),
                ('data_vinculacao', models.DateTimeField(auto_now_add=True, db_column='dt_vinculacao', help_text='Data quando o cliente foi vinculado a este usuário')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='devolucao.cliente')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='clientes_vinculados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente Vinculado',
                'verbose_name_plural': 'Clientes Vinculados',
                'db_table': 'tb_cliente_vinculado',
            },
        ),
        migrations.AddIndex(
            model_name='clientevinculado',
            index=models.Index(fields=['usuario', 'ativo'], name='tb_cliente__id_usua_aceaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='clientevinculado',
            index=models.Index(fields=['cliente'], name='tb_cliente__id_clie_56378c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientevinculado',
            unique_together={('usuario', 'cliente')},
        ),
    ]
