# Generated by Django 4.2 on 2026-04-07 16:16

from django.db import migrations


def populate_clientevinculado(apps, schema_editor):
    """
    Popula ClienteVinculado com relacionamentos existentes OneToOne.
    
    Para cada Cliente que tem usuario_id preenchido (OneToOne), cria
    um ClienteVinculado com ativo=True.
    """
    Cliente = apps.get_model('devolucao', 'Cliente')
    ClienteVinculado = apps.get_model('devolucao', 'ClienteVinculado')
    
    # Busca all clientes com usuario_id preenchido
    clientes_com_usuario = Cliente.objects.filter(usuario_id__isnull=False)
    
    total = 0
    for cliente in clientes_com_usuario:
        # Cria ClienteVinculado (skip duplicatas com unique_together)
        cv, created = ClienteVinculado.objects.get_or_create(
            usuario_id=cliente.usuario_id,
            cliente_id=cliente.id,
            defaults={'ativo': True}
        )
        if created:
            total += 1
    
    print(f'✓ Populado {total} ClienteVinculado a partir de OneToOne existentes')


def depopulate_clientevinculado(apps, schema_editor):
    """
    Remove ClienteVinculado criados pela migração forward.
    Apenas para rollback — dados criados durante a migração são removidos.
    """
    ClienteVinculado = apps.get_model('devolucao', 'ClienteVinculado')
    count = ClienteVinculado.objects.all().delete()[0]
    print(f'✓ Removido {count} ClienteVinculado durante rollback')


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0004_create_clientevinculado'),
    ]

    operations = [
        migrations.RunPython(populate_clientevinculado, depopulate_clientevinculado),
    ]
