# Generated by Django 4.2 on 2026-04-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0005_populate_clientevinculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='observacao_interna',
            field=models.TextField(blank=True, db_column='obs_interna', null=True, verbose_name='Observação Interna (Admin)'),
        ),
    ]
