# Generated by Django 4.2 on 2026-04-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0006_devolucao_observacao_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('devolvida', 'Devolvida parcialmente')], db_column='status', default='ativa', max_length=20),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='valor_total',
            field=models.DecimalField(blank=True, db_column='vlr_total', decimal_places=2, max_digits=12, null=True),
        ),
    ]
