# Generated by Django 5.2.7 on 2025-10-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, db_column='cnpj', max_length=14)),
                ('razao_social', models.CharField(blank=True, db_column='razao_soc', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'tb_cliente',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, db_column='codprod', null=True, unique=True)),
                ('descricao', models.CharField(blank=True, db_column='descricao', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'tb_produto',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(blank=True, db_column='nunota', max_length=50, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDevolucao.cliente')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'db_table': 'tb_notafiscal',
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(db_column='qtd')),
                ('nota_fiscal', models.ForeignKey(db_column='id_notafiscal', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='AppDevolucao.notafiscal')),
                ('produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.PROTECT, to='AppDevolucao.produto')),
            ],
            options={
                'verbose_name': 'Item da Nota',
                'verbose_name_plural': 'Itens da Nota',
                'db_table': 'tb_itens_nota',
            },
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_devolvida', models.PositiveIntegerField(blank=True, db_column='qtd_devolvida', null=True)),
                ('motivo', models.CharField(blank=True, choices=[('produto_danificado', 'Produto danificado'), ('erro_pedido', 'Erro no pedido'), ('prazo_vencido', 'Prazo de validade vencido'), ('outro', 'Outro')], db_column='motivo', max_length=200, null=True)),
                ('observacao', models.CharField(blank=True, db_column='obs', max_length=100, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDevolucao.cliente')),
                ('nota_fiscal', models.ForeignKey(db_column='id_notafiscal', on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='AppDevolucao.notafiscal')),
                ('produto', models.ForeignKey(blank=True, db_column='codprod', null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDevolucao.produto', to_field='codigo')),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
                'db_table': 'tb_devolucao',
            },
        ),
    ]
